### ISSUE TITLE
Small emoji preview images are more blurry than actual emoji once added to Slack

### ISSUE THREAD

**Issue by mikemacdev** [target/emoji_manager#43]
<img width="162" alt="Screenshot 2023-11-15 at 2 27 23 PM" src="https://github.com/target/emoji_manager/assets/24493256/2ee8550d-77b3-45df-b660-24356c21cb35">

Small emoji image previews look less blurry, more similar to actual emoji that gets rendered in Slack.  Right now they look significantly more blurry than they end up looking in slack, causing people to downvote proposals more often than they would if they could see a better preview.  See attached screenshot as an example.

I did some digging.  Looks like the small image preview (which is the most blurry), is generated here: https://github.com/target/emoji_manager/blob/main/src/main/kotlin/com/target/slack/ImageHelp.kt#L154

It is using the default scaling algorithm from the scrimage library, which is Bicubic.  Maybe there's a better scaling algorithm for the small size of preview images that are generated?
https://sksamuel.github.io/scrimage/scale/

### Requirements
  
Please read the [Contributing guidelines](https://github.com/target/emoji_manager/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/target/.github/blob/main/CODE_OF_CONDUCT.md) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by CrystalSpore** [comment]
I see that Lanczos3 is available. I've had good luck with this for all my image editing needs in the past.

**Comment by slushpupie** [comment]
Seems like it would be easy enough to try, I'll see about getting this in.
